version: '3.8'
services:
  nginx:
    image: developerchoims/my-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - react
      - spring
  react:
    image: developerchoims/my-react-app:latest
    ports:
      - "3000:3000"
  spring:
    image: developerchoims/my-spring-boot-app:latest
    ports:
      - "8080:8080"