version: '3.8'

services:
  spring:
    build:
      context: ./hoopi
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "8080:8080"
    networks:
      - my-network

  react:
    build:
      context: ./hoopifront
      dockerfile: Dockerfile
    container_name: react_app
    networks:
      - my-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - spring
      - react
    networks:
      - my-network

networks:
  my-network:
    driver: bridge