version: '3.8'

services:
  spring:
    build:
      context: ./hoopi
      dockerfile: Dockerfile
    image: developerchoims/spring:latest
    container_name: spring
    ports:
      - "8080:8080"
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '0.5'     # CPU 사용량 제한
          memory: 512M    # 메모리 사용량 제한


  react:
    build:
      context: ./hoopifront
      dockerfile: Dockerfile
    image: developerchoims/react:latest
    container_name: react
    ports:
      - "3000:80"
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '0.5'     # CPU 사용량 제한
          memory: 512M    # 메모리 사용량 제한


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: developerchoims/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - react
      - spring
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '0.5'     # CPU 사용량 제한
          memory: 512M    # 메모리 사용량 제한


networks:
  my-network:
    driver: bridge