version: '3.8'

services:
  spring:
    build:
      context: ./hoopi
      dockerfile: Dockerfile
    volumes:
      - ./hoopi/src/main/resources/application.yml:/app/application.yml
    container_name: spring
    ports:
      - "8080:8080"
    networks:
      - my-network

  react:
    build:
      context: ./hoopifront
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:80"
    networks:
      - my-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - react
      - spring
    networks:
      - my-network

networks:
  my-network:
    driver: bridge