version: '3.8'

services:
  nginx:
    image: developerchoims/my-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - react
      - spring
    networks:
      - my-network

  react:
    image: developerchoims/my-react-app:latest
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - my-network

  spring:
    image: developerchoims/my-spring-boot-app:latest
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - react
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
