version: '3.8'

services:
  nginx:
    image: developerchoims/my-nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react
      - spring

  react:
    image: developerchoims/my-react-app:latest
    ports:
      - "3000:80"

  spring:
    image: developerchoims/my-spring-boot-app:latest
    ports:
      - "8080:8080"