version: '3.8'

services:
  react-app:
    build:
      context: ./hoopifront
    ports:
      - "3000:80"


  spring-boot-app:
    build:
      context: ./hoopi
    ports:
      - "8080:8080"


  nginx:
    build:
      context: ./hoopifront/nginx
    ports:
      - "80:80"
    depends_on:
      - react-app
      - spring-boot-app