version: '3.8'

services:
  spring:
    build:
      context: ./hoopi
      dockerfile: Dockerfile
    image: developerchoims/my-spring-boot-app:latest
    container_name: spring
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.yml:/app/config/application.yml
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: developerchoims/my-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - spring
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  my-network:
    driver: bridge