package com.ms.hoopi.constants;

public class Constants {
    public static final String NONE_USER = "해당 아이디가 존재하지 않습니다.";
    public static final String INVALID_PWD = "비밀번호를 잘못 입력하셨습니다.";
    public static final String LOGIN_SUCCESS = "로그인에 성공하였습니다.";
    public static final String LOGIN_FAIL = "로그인에 실패하였습니다.";
    public static final String ALREADY_LOGOUT = "이미 로그아웃 하셨습니다..";
    public static final String LOGOUT_SUCCESS = "로그아웃에 성공하였습니다.";
    public static final String LOGOUT_FAIL = "로그아웃에 실패하였습니다.";
    public static final String ALREADY_EXIST = "이미 존재합니다.";
    public static final String JOIN_FAIL = "회원가입에 실패하였습니다.";
    public static final String JOIN_SUCCESS = "회원가입에 성공하였습니다.";
    public static final String REFRESH_ID_NOT_FOUND = "회원 정보를 확인할 수가 없습니다.";
    public static final String REFRESH_NOT_FOUND = "리프레시 토큰이 존재하지 않습니다.";
    public static final String JWT_INVALID = "토큰이 유효하지 않습니다.";
    public static final String ADDRESS_NOT_STORED = "주소가 저장되지 않았습니다.";
    public static final String USER_DETAIL_NOT_FOUND = "회원의 상세 정보를 확인할 수 없습니다.";
    public static final String USER_ORDER_NOT_FOUND = "회원의 주문 정보를 확인할 수 없습니다.";
    public static final String USER_QUIT_FAIL = "회원을 탈퇴시키는 과정에서 오류가 발생했습니다.";
    public static final String USER_QUIT_SUCCESS = "회원 탈퇴 처리가 완료되었습니다.";
    public static final String USER_UPDATE_FAIL = "회원 수정 처리 중에 오류가 발생하였습니다.";
    public static final String USER_UPDATE_SUCCESS = "회원 수정 처리가 완료되었습니다.";
    public static final String ARTICLE_SUCCESS = "게시글 작성이 완료되었습니다.";
    public static final String ARTICLE_FAIL = "게시글 작성에 실패하였습니다.";
    public static final String NONE_BOARD = "게시판 정보를 찾을 수 없습니다.";
    public static final String FILE_UPLOAD_FAIL = "파일 업로드에 실패하였습니다.";
    public static final String AWS_S3_FAIL = "S3에 파일을 업로드 하는 중에 문제가 발생하였습니다.";
    public static final String AWS_S3_CLIENT_FAIL = "AWS S3 CLIENT 문제입니다.";
    public static final String NONE_PRODUCT = "상품 정보를 찾을 수 없습니다.";
    public static final String NONE_ARTICLE = "게시글 정보를 찾을 수 없습니다.";
    public static final String NONE_CART = "장바구니 정보를 찾을 수 없습니다.";
    public static final String CART_ADD_SUCCESS = "상품을 장바구니에 추가했습니다.";
    public static final String CART_ADD_FAIL = "상품을 장바구니에 추가하는 중에 문제가 발생하였습니다.";
    public static final String CART_UPDATE_SUCCESS = "상품 수량을 수정하였습니다.";
    public static final String CART_UPDATE_FAIL = "상품 수량을 수정하는 중에 문제가 발생하였습니다.";
    public static final String CART_DELETE_SUCCESS = "장바구니에 담긴 상품을 삭제하였습니다.";
    public static final String CART_DELETE_FAIL = "장바구니에 담긴 상품을 삭제하는 중 문제가 발생하였습니다.";
    public static final String NONE_CART_PRODUCT = "장바구니에 담긴 상품 정보를 찾을 수 없습니다.";
    public static final String ORDER_SUCCESS = "주문이 완료되었습니다.";
    public static final String ORDER_FAIL = "주문 중에 문제가 발생하였습니다.";
    public static final String ORDER_FAIL_DO_NOT_MATCH = "주문 금액이 일치하지 않아 문제가 발생하였습니다.";
    public static final String ORDER_FAIL_VIRTUAL_ACCOUNT = "주문 중에 계좌 문제로 오류가 발생하였습니다.";
    public static final String ORDER_INVALID_REQUEST = "요청된 입력 정보가 유효하지 않습니다.";
    public static final String ORDER_UNAUTHORIZED = "인증 정보가 올바르지 않습니다.";
    public static final String ORDER_FORBIDDEN = "요청이 거절되었습니다.";
    public static final String ORDER_PAYMENT_NOT_FOUND = "결제 건이 존재하지 않습니다.";
    public static final String ORDER_PG = "Pg사에서 에러를 전달했습니다.";
    public static final String ORDER_GET_FAIL = "주문 정보를 불러오지 못했습니다.";
    public static final String NONE_PAYMENT = "결제 정보를 불러올 수 없습니다.";
    public static final String NONE_ORDER = "주문 정보를 불러올 수 없습니다.";
    public static final String ALREADY_DELIEVERED = "이미 발송되어 환불이 불가능합니다.";
    public static final String FORBIDDEN_ERROR = "요청이 거절되었습니다.";
    public static final String PAYMENT_ALREADY_CANCELLDED_ERROR = "결제가 이미 취소되었습니다.";
    public static final String PAYMENT_ERROR = "결제 취소에 실패하였습니다.";
    public static final String PAYMENT_CANCEL_SUCCESS = "결제 취소에 성공하였습니다.";
    public static final String ADDRESS_DELETE_SUCCESS = "주소가 삭제되었습니다.";
    public static final String ADDRESS_DELETE_FAIL = "주소 삭제에 실패하였습니다.";
    public static final String ADDRESS_JUST_ONE = "주소가 하나 뿐이라 삭제할 수 없습니다.";
    public static final String ADDRESS_ADD_SUCCESS = "주소 추가에 성공하였습니다.";
    public static final String ADDRESS_ADD_FAIL = "주소 추가에 실패하였습니다.";
    public static final String ADDRESS_ALREADY_MAIN = "이미 메인 주소로 설정되어 있습니다.";
    public static final String ADDRESS_MAIN_SUCCESS = "메인 주소로 설정되었습니다.";
    public static final String ADDRESS_MAIN_FAIL = "메인 주소 설정에 실패하였습니다.";


}
