name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create application.yml
        run: |
          cd ./hoopi/src/main/resources
          echo "${{ secrets.PROPERTIES }}" > application.yml
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push React Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./hoopifront
          file: ./hoopifront/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/my-react-app:latest

      - name: Build and push Spring Boot Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./hoopi
          file: ./hoopi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/my-spring-boot-app:latest

      - name: Build and push Nginx Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/my-nginx:latest

      - name: Copy docker-compose.yml to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          # Save SSH private key to a file
          echo "$SSH_KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          # Copy docker-compose.yml to the server, overwrite if exists
          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa docker-compose.yml ec2-user@$SSH_HOST:/home/ec2-user/docker-compose.yml

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          # Save SSH private key to a file
          echo "$SSH_KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
        
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@$SSH_HOST << EOF
            cd /home/ec2-user
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF
